Update latest-stable
nvims

diff --git a/template/bin/latest-stable b/template/bin/latest-stable
--- a/template/bin/latest-stable
+++ b/template/bin/latest-stable
@@ -1,29 +1,73 @@
 #!/usr/bin/env bash
 
+set -e
 set -euo pipefail
 
-current_script_path=${BASH_SOURCE[0]}
-plugin_dir=$(dirname "$(dirname "$current_script_path")")
+export LATEST_NVIMS_VERSION="master"
+export DEFAULT_NVIMS_REPO="https://github.com/Traap/nvims.git"
+
+# current_script_path=${BASH_SOURCE[0]}
+# plugin_dir=$(dirname "$(dirname "$current_script_path")")
+
+fail() {
+  echo -e "\e[31mFail:\e[m $*"
+  exit 1
+}
+
+download_nvims () {
+  	local version=$1
+	local download_path=$2
+	local repo_url=$3
+(
+    echo "* Downloading nvims (version:$version) to $download_path"
+	git clone --depth=1 "$repo_url" "$download_path" >/dev/null
+    echo "Download successful."
+    return 0
+
+) || (
+    fail "An error occured during download - check if $version exists"
+  )
+}
+
+
+version=${1:-"$ASDF_INSTALL_VERSION"}
+if [[ -z "$version" ]] ; then
+  fail "Version is missing - specify 1st param or set \$ASDF_INSTALL_VERSION"
+fi
+
+download_path=${2:-"$ASDF_DOWNLOAD_PATH"}
+if [[ -z "$download_path" ]] ; then
+  fail "Download path is missing - specify 2nd param or set \$ASDF_DOWNLOAD_PATH"
+fi
+
+repo_url=${3:-"$DEFAULT_NVIMS_REPO"}
+if [[ -z "$repo_url" ]] ; then
+  fail "repo_url is missing - specify 3rd param"
+fi
+
+echo "Preparing downloading $version from $repo_url"
+download_nvims "$version" "$download_path" "$repo_url"
+
 
 # shellcheck source=./lib/utils.bash
-. "${plugin_dir}/lib/utils.bash"
+# . "${plugin_dir}/lib/utils.bash"
 
-curl_opts=(-sI)
+# curl_opts=(-sI)
 
-if [ -n "${GITHUB_API_TOKEN:-}" ]; then
-	curl_opts=("${curl_opts[@]}" -H "Authorization: token $GITHUB_API_TOKEN")
-fi
+# if [ -n "${GITHUB_API_TOKEN:-}" ]; then
+#	curl_opts=("${curl_opts[@]}" -H "Authorization: token $GITHUB_API_TOKEN")
+# fi
 
 # curl of REPO/releases/latest is expected to be a 302 to another URL
 # when no releases redirect_url="REPO/releases"
 # when there are releases redirect_url="REPO/releases/tag/v<VERSION>"
-redirect_url=$(curl "${curl_opts[@]}" "$GH_REPO/releases/latest" | sed -n -e "s|^location: *||p" | sed -n -e "s|\r||p")
-version=
-printf "redirect url: %s\n" "$redirect_url" >&2
-if [[ "$redirect_url" == "$GH_REPO/releases" ]]; then
-	version="$(list_all_versions | sort_versions | tail -n1 | xargs echo)"
-else
-	version="$(printf "%s\n" "$redirect_url" | sed 's|.*/tag/v\{0,1\}||')"
-fi
+# redirect_url=$(curl "${curl_opts[@]}" "$GH_REPO/releases/latest" | sed -n -e "s|^location: *||p" | sed -n -e "s|\r||p")
+# version=
+# printf "redirect url: %s\n" "$redirect_url" >&2
+# if [[ "$redirect_url" == "$GH_REPO/releases" ]]; then
+	# version="$(list_all_versions | sort_versions | tail -n1 | xargs echo)"
+# else
+#	version="$(printf "%s\n" "$redirect_url" | sed 's|.*/tag/v\{0,1\}||')"
+# fi
 
-printf "%s\n" "$version"
+# printf "%s\n" "$version"
